### ISSUE TITLE
Crash after end of scenario 046

### ISSUE THREAD

**Issue by Mykimus** [Lurkars/gloomhavensecretariat#639]
### Describe the bug

We had just finished scenario 046 (Dead Pass). We were done viewing the scenario complete screen and clicked "Finish." That's when the crash occurred.

### Game Enviroment

Version 0.105.6
Scenario 046
Server running on Windows. 
Two clients running. One on localhost (Chrome) and one remote on local network (Edge). 

### To Reproduce

(Not sure if it is reproducible.) 
1. Go to end of scenario 046
2. Click on scenario complete
3. Scroll down to bottom of Scenario Complete screen and click Finish

### Expected behavior

Expected the scenario to finish successfully.

### Gloomhaven Secretariat Version

0.105.6

### Used Browser

Chrome 

### OS

Windows 11

### Additional

ERROR Stack Trace:

Cannot read properties of undefined (reading '0')

TypeError: Cannot read properties of undefined (reading '0')
    at http://10.0.14.7:8080/main.b18f7463a49c402a.js:48:795999
    at Array.forEach (<anonymous>)
    at http://10.0.14.7:8080/main.b18f7463a49c402a.js:48:795895
    at Generator.next (<anonymous>)
    at m (http://10.0.14.7:8080/main.b18f7463a49c402a.js:99:2096)
    at Q (http://10.0.14.7:8080/main.b18f7463a49c402a.js:99:2300)
    at http://10.0.14.7:8080/main.b18f7463a49c402a.js:99:2359
    at S (http://10.0.14.7:8080/polyfills.2951700afa6a269f.js:6:27441)
    at http://10.0.14.7:8080/main.b18f7463a49c402a.js:99:2241
    at o.finish (http://10.0.14.7:8080/main.b18f7463a49c402a.js:48:798750)
[ghs-data-dump (8).json](https://github.com/user-attachments/files/18216908/ghs-data-dump.8.json)

**Comment by Lurkars** [comment]
It's not reproducable by me, so best so send Data Dump via E-mail to me, use the feedback dialog for this.
